/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "border-low-contrast": "#E2E4E9",
        "outline": "#767684",
        "surface-subtle": "#F7F8F9",
        "surface-dim": "#dbdad9",
        "inverse-on-surface": "#f2f0f0",
        "text-primary": "#111111",
        "surface-container-high": "#e9e8e8",
        "secondary-fixed-dim": "#c8c6c5",
        "error": "#ba1a1a",
        "surface-tint": "#4854bb",
        "on-tertiary-fixed": "#2b1700",
        "on-error": "#ffffff",
        "primary": "#4450b7",
        "tertiary-fixed": "#ffddbb",
        "on-secondary-container": "#656464",
        "secondary-container": "#e5e2e1",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#673d00",
        "on-primary-fixed": "#000965",
        "surface-variant": "#e3e2e2",
        "tertiary-container": "#a56500",
        "outline-variant": "#c6c5d5",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#bdc2ff",
        "inverse-surface": "#303031",
        "primary-container": "#5e6ad2",
        "on-primary-container": "#fdfaff",
        "on-surface": "#1b1c1c",
        "tertiary-fixed-dim": "#ffb867",
        "on-background": "#1b1c1c",
        "surface-container-highest": "#e3e2e2",
        "surface-container-low": "#f5f3f3",
        "on-primary-fixed-variant": "#2e3aa2",
        "text-secondary": "#555555",
        "on-surface-variant": "#454652",
        "surface": "#faf9f9",
        "on-secondary-fixed-variant": "#474646",
        "surface-base": "#FFFFFF",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary": "#834f00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffaf8",
        "primary-fixed": "#dfe0ff",
        "inverse-primary": "#bdc2ff",
        "surface-container": "#efeded",
        "surface-bright": "#faf9f9",
        "on-secondary-fixed": "#1c1b1b",
        "background": "#faf9f9",
        "secondary-fixed": "#e5e2e1",
        "secondary": "#5f5e5e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit-4": "16px",
        "unit-8": "32px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit-2": "8px",
        "unit-12": "48px",
        "unit-1": "4px",
        "container-max": "1280px",
        "base": "4px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
